echo test | aaaa | echo test2
echo test2 | bbb | echo test3
echo test | aaaa | echo test2
echo test2 | bbb | echo test3
echo test | aaaa | echo test2
echo test2 | bbb | echo test3
echo test | aaaa | echo test2
echo test2 | bbb | echo test3
echo test | aaaa | echo test2
echo test2 | bbb | echo test3
echo test | aaaa | echo test2
echo test2 | bbb | echo test3
echo test | aaaa | echo test2
echo test2 | bbb | echo test3
echo test | aaaa | echo test2
echo test2 | bbb | echo test3
echo test | aaaa | echo test2
echo test2 | bbb | echo test3
echo test | aaaa | echo test2
echo test2 | bbb | echo test3
echo test | aaaa | echo test2
echo test2 | bbb | echo test3
echo test | aaaa | echo test2
echo test2 | bbb | echo test3
echo test | aaaa | echo test2
echo test2 | bbb | echo test3
echo test | aaaa | echo test2
echo test2 | bbb | echo test3
echo test | aaaa | echo test2
echo test2 | bbb | echo test3
echo test | aaaa | echo test2
echo test2 | bbb | echo test3
echo test | aaaa | echo test2
echo test2 | bbb | echo test3
echo test | aaaa | echo test2
echo test2 | bbb | echo test3
echo test | aaaa | echo test2
echo test2 | bbb | echo test3
echo test | aaaa | echo test2
echo test2 | bbb | echo test3
echo test | aaaa | echo test2
echo test2 | bbb | echo test3
echo test | aaaa | echo test2
echo test2 | bbb | echo test3
echo test | aaaa | echo test2
echo test2 | bbb | echo test3
echo test | aaaa | echo test2
echo test2 | bbb | echo test3
echo test | aaaa | echo test2
echo test2 | bbb | echo test3
echo test | aaaa | echo test2
echo test2 | bbb | echo test3
echo test | aaaa | echo test2
echo test2 | bbb | echo test3
echo test | aaaa | echo test2
echo test2 | bbb | echo test3
echo test | aaaa | echo test2
echo test2 | bbb | echo test3
echo test | aaaa | echo test2
echo test2 | bbb | echo test3
echo test | aaaa | echo test2
echo test2 | bbb | echo test3
echo test | aaaa | echo test2
echo test2 | bbb | echo test3
echo test | aaaa | echo test2
echo test2 | bbb | echo test3
echo test | aaaa | echo test2
echo test2 | bbb | echo test3
echo test | aaaa | echo test2
echo test2 | bbb | echo test3
echo test | aaaa | echo test2
echo test2 | bbb | echo test3
echo test | aaaa | echo test2
echo test2 | bbb | echo test3
echo test | aaaa | echo test2
echo test2 | bbb | echo test3
echo test | aaaa | echo test2
echo test2 | bbb | echo test3
echo test | aaaa | echo test2
echo test2 | bbb | echo test3
echo test | aaaa | echo test2
echo test2 | bbb | echo test3
echo test | aaaa | echo test2
echo test2 | bbb | echo test3
echo test | aaaa | echo test2
echo test2 | bbb | echo test3
echo test | aaaa | echo test2
echo test2 | bbb | echo test3
echo test | aaaa | echo test2
echo test2 | bbb | echo test3
echo test | aaaa | echo test2
echo test2 | bbb | echo test3
echo test | aaaa | echo test2
echo test2 | bbb | echo test3
echo test | aaaa | echo test2
echo test2 | bbb | echo test3
echo test | aaaa | echo test2
echo test2 | bbb | echo test3
echo test | aaaa | echo test2
echo test2 | bbb | echo test3
echo test | aaaa | echo test2
echo test2 | bbb | echo test3
echo test | aaaa | echo test2
echo test2 | bbb | echo test3
echo test | aaaa | echo test2
echo test2 | bbb | echo test3
echo test | aaaa | echo test2
echo test2 | bbb | echo test3
echo test | aaaa | echo test2
echo test2 | bbb | echo test3
echo test | aaaa | echo test2
echo test2 | bbb | echo test3
echo test | aaaa | echo test2
echo test2 | bbb | echo test3
echo test | aaaa | echo test2
echo test2 | bbb | echo test3
echo test | aaaa | echo test2
echo test2 | bbb | echo test3
echo test | aaaa | echo test2
echo test2 | bbb | echo test3
echo test | aaaa | echo test2
echo test2 | bbb | echo test3
echo test | aaaa | echo test2
echo test2 | bbb | echo test3
echo test | aaaa | echo test2
echo test2 | bbb | echo test3
echo test | aaaa | echo test2
echo test2 | bbb | echo test3
echo test | aaaa | echo test2
echo test2 | bbb | echo test3
echo test | aaaa | echo test2
echo test2 | bbb | echo test3
echo test | aaaa | echo test2
echo test2 | bbb | echo test3
echo test | aaaa | echo test2
echo test2 | bbb | echo test3
echo test | aaaa | echo test2
echo test2 | bbb | echo test3
echo test | aaaa | echo test2
echo test2 | bbb | echo test3
echo test | aaaa | echo test2
echo test2 | bbb | echo test3
echo test | aaaa | echo test2
echo test2 | bbb | echo test3
echo test | aaaa | echo test2
echo test2 | bbb | echo test3
echo test | aaaa | echo test2
echo test2 | bbb | echo test3
echo test | aaaa | echo test2
echo test2 | bbb | echo test3
echo test | aaaa | echo test2
echo test2 | bbb | echo test3
echo test | aaaa | echo test2
echo test2 | bbb | echo test3
echo test | aaaa | echo test2
echo test2 | bbb | echo test3
echo test | aaaa | echo test2
echo test2 | bbb | echo test3
echo test | aaaa | echo test2
echo test2 | bbb | echo test3
echo test | aaaa | echo test2
echo test2 | bbb | echo test3
echo test | aaaa | echo test2
echo test2 | bbb | echo test3
echo test | aaaa | echo test2
echo test2 | bbb | echo test3
echo test | aaaa | echo test2
echo test2 | bbb | echo test3
echo test | aaaa | echo test2
echo test2 | bbb | echo test3
echo test | aaaa | echo test2
echo test2 | bbb | echo test3
echo test | aaaa | echo test2
echo test2 | bbb | echo test3
echo test | aaaa | echo test2
echo test2 | bbb | echo test3
echo test | aaaa | echo test2
echo test2 | bbb | echo test3
echo test | aaaa | echo test2
echo test2 | bbb | echo test3
